### ISSUE TITLE
Version missmatch and Redirect loop detected

### ISSUE THREAD

**Issue by lordravo** [GoogleCloudDataproc/jupyterhub-dataprocspawner#4]
It seems the version pulled on dockerfile "1.0.1dev" is missmatching with the dataproc clusters version "1.0"

Furthermore, the latest version appears to have some kind of template issues..
I need to add the following to the jupyterhub_config.py to successfully load the login page:

c.JupyterHub.data_files_path = '/usr/local/share/jupyterhub'

Still can't manage to make it work though, because after the cluster is provisioned and running, I keep getting:

500 : Internal Server Error
Redirect loop detected.

Any ideas?

**Comment by karth295** [comment]
Ah yeah we should pin the Dockerfile in this repo to `1.0` to match Dataproc. Does it work if you change rebuild from 1.0?

**Comment by lordravo** [comment]
hi @karth295 .

I made a fork with a pin to `1.0.0` and it fixed the template issue;

But I'm still getting the redirect loop. Not sure why. Is it a firewall issue?

I was following the `Manual Docker Image` approach.
It successfully create the dataproc clusters with jupyter, but ends up with the following>

> [I 2019-12-10 14:31:45.098 JupyterHub log:174] 302 GET /hub/user/test/?redirects=1 -> /user/test/?redirects=2 (test@177.92.86.174) 2010.95ms
> [I 2019-12-10 14:31:45.225 JupyterHub log:174] 302 GET /user/test/?redirects=2 -> /hub/user/test/?redirects=2 (@177.92.86.174) 0.91ms
> [W 2019-12-10 14:31:45.358 JupyterHub base:1393] Redirect loop detected on /hub/user/test/?redirects=2

http://34.74.137.92:8081/hub/user/test/:

![image](https://user-images.githubusercontent.com/58708386/70538414-ced2cd80-1b40-11ea-94e7-6e6317931e1d.png)

While testing, allowing connections to port 8000, (iptables -w -A INPUT -p tcp --dport 8000 -j ACCEPT) I managed to achieve the jupyter path at:

http://34.74.137.92:8000/user/test/tree

![image](https://user-images.githubusercontent.com/58708386/70538643-3557eb80-1b41-11ea-9ada-c5e89225852f.png)

So, i cannot pass through the `Spawning server...` step directly to the jupyter. I have to wait untill it gets a redirect loop, and then launch jupyter pointing to its path

Am I missing something?

Thanks!

**Comment by Kopaniev** [comment]
I have the same problem. 

I try to start a new server for my user, and got the following error in the browser:

![image](https://user-images.githubusercontent.com/2806614/72255733-2963bb80-3610-11ea-8b90-b9169f263e80.png)

Server logs:

```
I 2020-01-13 12:23:38.829 JupyterHub dataprocspawner:194] ju-jupyterhub is up and running
[I 2020-01-13 12:23:43.841 JupyterHub dataprocspawner:194] ju-jupyterhub is up and running
[I 2020-01-13 12:23:44.200 JupyterHub log:174] 302 GET /user/ju -> /user/ju/ (@<my_ip>) 0.85ms
[I 2020-01-13 12:23:44.340 JupyterHub log:174] 302 GET /user/ju/ -> /hub/user/ju/ (@<my_ip>) 0.79ms
[I 2020-01-13 12:23:44.488 JupyterHub log:174] 302 GET /hub/user/ju/ -> /user/ju/ (ju@<my_ip>) 9.05ms
I 2020-01-13 12:23:47.431 JupyterHub log:174] 302 GET /user/ju/?redirects=1 -> /hub/user/ju/?redirects=1 (@<my_ip>) 0.77ms
[W 2020-01-13 12:23:47.581 JupyterHub base:1393] Redirect loop detected on /hub/user/ju/?redirects=1
[I 2020-01-13 12:23:48.830 JupyterHub dataprocspawner:194] ju-jupyterhub is up and running
[I 2020-01-13 12:23:49.584 JupyterHub log:174] 302 GET /hub/user/ju/?redirects=1 -> /user/ju/?redirects=2 (ju@<my_ip>) 2011.10ms
[I 2020-01-13 12:23:49.724 JupyterHub log:174] 302 GET /user/ju/?redirects=2 -> /hub/user/ju/?redirects=2 (@<my_ip>) 0.80ms
[W 2020-01-13 12:23:49.871 JupyterHub base:1393] Redirect loop detected on /hub/user/ju/?redirects=2
[I 2020-01-13 12:23:53.829 JupyterHub dataprocspawner:194] ju-jupyterhub is up and running
[I 2020-01-13 12:23:53.873 JupyterHub log:174] 302 GET /hub/user/ju/?redirects=2 -> /user/ju/?redirects=3 (ju@<my_ip>) 4010.43ms
[I 2020-01-13 12:23:54.012 JupyterHub log:174] 302 GET /user/ju/?redirects=3 -> /hub/user/ju/?redirects=3 (@<my_ip>) 0.78ms
[W 2020-01-13 12:23:54.160 JupyterHub base:1393] Redirect loop detected on /hub/user/ju/?redirects=3
[I 2020-01-13 12:23:58.828 JupyterHub dataprocspawner:194] ju-jupyterhub is up and running
[I 2020-01-13 12:24:02.163 JupyterHub log:174] 302 GET /hub/user/ju/?redirects=3 -> /user/ju/?redirects=4 (ju@<my_ip>) 8010.73ms
[I 2020-01-13 12:24:02.335 JupyterHub log:174] 302 GET /user/ju/?redirects=4 -> /hub/user/ju/?redirects=4 (@<my_ip>) 0.83ms
[W 2020-01-13 12:24:02.521 JupyterHub web:1782] 500 GET /hub/user/ju/?redirects=4 (<my_ip>): Redirect loop detected.
[E 2020-01-13 12:24:02.523 JupyterHub log:166] {
      "Connection": "keep-alive",
      "Cache-Control": "max-age=0",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.9,uk;q=0.8",
      "Cookie": "jupyterhub-hub-login=[secret]; jupyterhub-session-id=[secret]"
    }
[E 2020-01-13 12:24:02.523 JupyterHub log:174] 500 GET /hub/user/ju/?redirects=4 (ju@<my_ip>) 10.66ms
[I 2020-01-13 12:24:03.826 JupyterHub dataprocspawner:194] ju-jupyterhub is up and running
[I 2020-01-13 12:24:08.828 JupyterHub dataprocspawner:194] ju-jupyterhub is up and running
```

**Comment by Kopaniev** [comment]
I've found the same issue on the jupiterhub repo: 
https://github.com/jupyterhub/jupyterhub/issues/2364
I've tried to fix the issue by the described their way, just open jupiterhub via "http://ip:8000", but in this way, I got 404 instead of a notebook.

**Comment by m-mayran** [comment]
A request to notebook now gets redirected and not proxies to Dataproc notebooks if exists. This error should not happen anymore.
