### ISSUE TITLE
Dataproc Hub - Multiple user for a Dataproc cluster

### ISSUE THREAD

**Issue by dineshvelmuruga** [GoogleCloudDataproc/jupyterhub-dataprocspawner#45]
Is it possible for multiple user to use JupyterLab that is hosted on a Dataproc cluster?

**Comment by m-mayran** [comment]
Currently, multiple users can use the Component Gateway URL to use the same (ie not sandboxed) JupyterLab environment on a Dataproc cluster.

For more details about the Component Gateway URL, you can read https://cloud.google.com/dataproc/docs/concepts/accessing/dataproc-gateways#considerations

This behavior is independent of Dataproc Hub which is a control plane that allows administrators to created pre-defined environments for teams of users who don't have Dataproc admin-like permissions.
