### ISSUE TITLE
Dataproc Hub User Spawned cluster creation - Unable to disable component gateway in the new cluster created

### ISSUE THREAD

**Issue by mdsb** [GoogleCloudDataproc/jupyterhub-dataprocspawner#61]
[](https://github.com/GoogleCloudDataproc/jupyterhub-dataprocspawner/blob/71b8b3cdf30c8f374279d20c086122b05a77f3af/dataprocspawner/spawner.py#L1468)

While creating a "User spawned cluster" from Dataproc Hub JupyterHub (based off a custom YAML config), unable to override the default value and set to "False", so that it does not show up in the UI of the Dataproc cluster

The below lines force the Dataproc spawner to enable the component gateway. Is there a way to set to false from the YAML configuration or through some flag.

Reason for this ask: In a team setup anyone can use this backdoor entry and get access to others notebooks, which they are not supposed to.

Link to code
 https://github.com/GoogleCloudDataproc/jupyterhub-dataprocspawner/blob/71b8b3cdf30c8f374279d20c086122b05a77f3af/dataprocspawner/spawner.py#L1468

```
 # Forces Component Gateway
    cluster_data['config'].setdefault('endpoint_config', {})
    cluster_data['config']['endpoint_config']['enable_http_port_access'] = True
```

**Comment by m-mayran** [comment]
This is an interesting point. 

After Dataproc Hub release uses #60 , there will be an option for users to set the cluster property `dataproc:dataproc.alpha.unified-auth.user` to their own email (if an admin sets `dataproc-allow-custom-clusters` to true which allows users to overwrite the default templates)

This is a work-around for now but I will investigate how we can make this more user friendly by not having to use dataproc-allow-custom-clusters and force the user to manually enter their email.

**Comment by m-mayran** [comment]
As a curiosity, in your current setup, how would User A get access to the URL of the notebook of User B?

**Comment by mdsb** [comment]
@m-mayran  - Than you for taking time to look into this issue.
Steps to re-create in the current setup,

1. Spin up the "Dataproc Hub Instance"  (User A and User B both have access to this instance)
2. User A  -->  Dataproc > Notebooks > "Open JupyterLab" > On JupyterHub page > Cluster configuration dropdown > Choose one configuration and spin up the cluster (User spawned cluster) 
3. User B  -->   Dataproc > Clusters > Choose the cluster spun up by USER A > Open Web Interfaces tab > Choose JupyterLab

**Comment by m-mayran** [comment]
1. At the Hub level, #62 should provide a way for admin to set personal notebooks through a force_single_user flag. The admin needs to start the instance with a `force-single-user=true` metadata.

2. At the template level, an admin can export a cluster configuration with the property `dataproc:dataproc.personal-auth.user`. The code will automatically update it to the user identity.

3. At the user level, #60 allows users to it themselves if the admin allows custom clusters. User can use the `dataproc property dataproc:dataproc.personal-auth.user`. 

For 3., I am also considering at making this option as a checkbox outside of the custom cluster options. I think it would improve user experience. Let me know what you think.

**Comment by mdsb** [comment]
1.  LGTM
2. In my current setup, I'm using a Service Account with a group of users attached to it. In this scenario, would the code update to Service Account's identity or User's within that Service Account's identity.
3. LGTM - the explicit setting of the checkbox options for user experience. Hope, default value in the UI will be set to not to share. (since, this would remove the liability from the user)

Additional clarification question: I hope any of the above changes will not interfere if this feature ([in link](https://cloud.google.com/dataproc/docs/concepts/iam/personal-auth)) is extended to Dataproc Hub Instances. (Currently, its available only to Daraproc clusters and not Dataproc hub.)

**Comment by cxhercules** [comment]
@m-mayran how long before #62 is the prod tag, can I specify it via 62 as tag in here: `gcr.io/cloud-dataproc/dataproc-spawner:prod`. Also will there be a way to not allow users in same project to access jupyterlabs link? At the moment I been trying with separate service account for dataproc hub and separate account for clusters. I have given a particular user access to both, and then I have tried with another low priv user with same access as lets say user one, but without service account use for the dataproc hub or cluster service accounts. For dataproc hub it is restricted, great! But for the cluster I can get to the jupyterlab link and I can create files and run as the service account entity without having access to use that service account. Also even if we hide the link if someone gathers what the link is I thinking they will likely have same access?

**Comment by cxhercules** [comment]
Ok as far tags I answered part of my question I could do:
```
gcloud container images list-tags gcr.io/cloud-dataproc/dataproc-spawner
```

and no there is no 62 on there.

**Comment by m-mayran** [comment]
@mdsb :

For 2, the personal auth is to limit access to the Component Gateway URL, it does not modify the identity of the notebook service that runs on the instance (so by default it still use the service account). 

For 3, clusters created by Dataproc Hub instances are normal Dataproc clusters. The Hub is a control plane so when Personal Cluster Auth is GA, this is something that Dataproc Hub will aim at supporting.

---------------

@cxhercules :

- #62, #63 and #64 should be live with the next Dataproc Hub release in the next week or so. It will allow users to limit access to the Component Gateway URL but won't impact the identity of the notebook service.
- Propagating identity for the notebook service is related this [Beta](https://cloud.google.com/dataproc/docs/concepts/iam/personal-auth) but will not implemented in Dataproc Hub until the feature is GA.

**Comment by mdsb** [comment]
@m-mayran :
Response For 2: LGTM
Response For 3: LGTM
Could you also respond to this from above 3. - Hope, default value in the UI will be set to not to share. (since, this would remove the liability from the user)

**Comment by m-mayran** [comment]
Sure, unless the review thinks differently, the checkbox is [checked by detault](https://github.com/GoogleCloudDataproc/jupyterhub-dataprocspawner/pull/64/files#diff-4a5ffe744f84f2784cdcb56fe4ea98755486dc06ef6568bc2f70b744bab81c23R96).

**Comment by mdsb** [comment]
Sounds good to me.

**Comment by mdsb** [comment]
@m-mayran - Could you please tell, when these features scheduled for release.

**Comment by m-mayran** [comment]
Sorry for the delay. It is already live.
